### ISSUE TITLE
SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://adwords.google.com/api/adwords/mcm/v201705/ManagedCustomerService?wsdl'

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/adwords-extractor#13]
```
{
    "output": "",
    "errorOutput": "SOAP-ERROR: Parsing WSDL: Couldn't load from 'https:\/\/adwords.google.com\/api\/adwords\/mcm\/v201705\/ManagedCustomerService?wsdl' : Start tag expected, '<' not found\n\n#0 \/code\/vendor\/googleads\/googleads-php-lib\/src\/Google\/AdsApi\/Common\/AdsSoapClient.php(65): SoapClient->SoapClient('https:\/\/adwords...', Array)\n#1 \/code\/vendor\/googleads\/googleads-php-lib\/src\/Google\/AdsApi\/AdWords\/v201705\/mcm\/ManagedCustomerService.php(91): Google\\AdsApi\\Common\\AdsSoapClient->__construct('https:\/\/adwords...', Array)\n#2 [internal function]: Google\\AdsApi\\AdWords\\v201705\\mcm\\ManagedCustomerService->__construct(Array)\n#3 \/code\/vendor\/googleads\/googleads-php-lib\/src\/Google\/AdsApi\/Common\/Util\/Reflection.php(39): ReflectionClass->newInstanceArgs(Array)\n#4 \/code\/vendor\/googleads\/googleads-php-lib\/src\/Google\/AdsApi\/Common\/AdsSoapClientFactory.php(87): Google\\AdsApi\\Common\\Util\\Reflection->createInstance('Google\\\\AdsApi\\\\A...', Array)\n#5 \/code\/vendor\/googleads\/googleads-php-lib\/src\/Google\/AdsApi\/AdWords\/AdWordsServices.php(55): Google\\AdsApi\\Common\\AdsSoapClientFactory->generateSoapClient(Object(Google\\AdsApi\\AdWords\\AdWordsSession), Object(Google\\AdsApi\\AdWords\\AdWordsHeaderHandler), Object(Google\\AdsApi\\AdWords\\AdWordsServiceDescriptor))\n#6 \/code\/src\/Keboola\/AdWordsExtractor\/Api.php(138): Google\\AdsApi\\AdWords\\AdWordsServices->get(Object(Google\\AdsApi\\AdWords\\AdWordsSession), 'Google\\\\AdsApi\\\\A...')\n#7 \/code\/src\/Keboola\/AdWordsExtractor\/Extractor.php(78): Keboola\\AdWordsExtractor\\Api->getCustomersYielded('20180526', '20180527')\n#8 \/code\/src\/Keboola\/AdWordsExtractor\/RunCommand.php(51): Keboola\\AdWordsExtractor\\Extractor->extract(Array, '20180526', '20180527')\n#9 \/code\/vendor\/symfony\/console\/Command\/Command.php(264): Keboola\\AdWordsExtractor\\RunCommand->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#10 \/code\/vendor\/symfony\/console\/Application.php(869): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#11 \/code\/vendor\/symfony\/console\/Application.php(223): Symfony\\Component\\Console\\Application->doRunCommand(Object(Keboola\\AdWordsExtractor\\RunCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#12 \/code\/vendor\/symfony\/console\/Application.php(130): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#13 \/code\/src\/app.php(17): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#14 {main}",
    "container": {
        "id": "398273905-398272120.398273906--0-keboola-ex-adwords-v201705",
        "image": "147946154733.dkr.ecr.us-east-1.amazonaws.com\/developer-portal-v2\/keboola.ex-adwords-v201705:3.2.2"
    }
}
```

```
SOAP-ERROR: Parsing WSDL: Couldn't load from 'https:\/\/adwords.google.com\/api\/adwords\/mcm\/v201705\/ManagedCustomerService?wsdl' : Start tag expected, '<' not found

#0 \/code\/vendor\/googleads\/googleads-php-lib\/src\/Google\/AdsApi\/Common\/AdsSoapClient.php(65): SoapClient->SoapClient('https:\/\/adwords...', Array)
#1 \/code\/vendor\/googleads\/googleads-php-lib\/src\/Google\/AdsApi\/AdWords\/v201705\/mcm\/ManagedCustomerService.php(91): Google\\AdsApi\\Common\\AdsSoapClient->__construct('https:\/\/adwords...', Array)
#2 [internal function]: Google\\AdsApi\\AdWords\\v201705\\mcm\\ManagedCustomerService->__construct(Array)
#3 \/code\/vendor\/googleads\/googleads-php-lib\/src\/Google\/AdsApi\/Common\/Util\/Reflection.php(39): ReflectionClass->newInstanceArgs(Array)
#4 \/code\/vendor\/googleads\/googleads-php-lib\/src\/Google\/AdsApi\/Common\/AdsSoapClientFactory.php(87): Google\\AdsApi\\Common\\Util\\Reflection->createInstance('Google\\\\AdsApi\\\\A...', Array)
#5 \/code\/vendor\/googleads\/googleads-php-lib\/src\/Google\/AdsApi\/AdWords\/AdWordsServices.php(55): Google\\AdsApi\\Common\\AdsSoapClientFactory->generateSoapClient(Object(Google\\AdsApi\\AdWords\\AdWordsSession), Object(Google\\AdsApi\\AdWords\\AdWordsHeaderHandler), Object(Google\\AdsApi\\AdWords\\AdWordsServiceDescriptor))
#6 \/code\/src\/Keboola\/AdWordsExtractor\/Api.php(138): Google\\AdsApi\\AdWords\\AdWordsServices->get(Object(Google\\AdsApi\\AdWords\\AdWordsSession), 'Google\\\\AdsApi\\\\A...')
#7 \/code\/src\/Keboola\/AdWordsExtractor\/Extractor.php(78): Keboola\\AdWordsExtractor\\Api->getCustomersYielded('20180526', '20180527')
#8 \/code\/src\/Keboola\/AdWordsExtractor\/RunCommand.php(51): Keboola\\AdWordsExtractor\\Extractor->extract(Array, '20180526', '20180527')
#9 \/code\/vendor\/symfony\/console\/Command\/Command.php(264): Keboola\\AdWordsExtractor\\RunCommand->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#10 \/code\/vendor\/symfony\/console\/Application.php(869): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#11 \/code\/vendor\/symfony\/console\/Application.php(223): Symfony\\Component\\Console\\Application->doRunCommand(Object(Keboola\\AdWordsExtractor\\RunCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#12 \/code\/vendor\/symfony\/console\/Application.php(130): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#13 \/code\/src\/app.php(17): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#14 {main}
```

https://connection.keboola.com/admin/utils/logs?file=2018/05/28/02/2018-05-28-02-09-02-5b0b489e3b325-exception
https://connection.keboola.com/admin/utils/logs?file=2018/05/28/02/2018-05-28-02-09-02-5b0b489e7395d-log

**Comment by odinuv** [comment]
https://keboola.slack.com/archives/C09U3R1J4/p1528502646000038

**Comment by odinuv** [comment]
https://keboola.slack.com/archives/C09U3R1J4/p1528675569000048

**Comment by JakubMatejka** [comment]
Fixed by https://github.com/keboola/adwords-extractor/releases/tag/5.1.1
