### ISSUE TITLE
bad gateway

### ISSUE THREAD

**Issue by odinuv** [keboola/adwords-extractor#16]
objevilo se to jednou, takze bych to zatim neresil, issue delam abysme kdyztak vedeli jestli se to opakuje

(2) Server error: `POST https://www.googleapis.com/oauth2/v4/token` resulted in a `502 Bad Gateway` response:
<!DOCTYPE html>(truncated...)

#0 /code/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#10 /code/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsGuzzleProxyHttpHandler.php(63): GuzzleHttp\Client->send(Object(GuzzleHttp\Psr7\Request), Array)
#11 /code/vendor/google/auth/src/OAuth2.php(501): Google\AdsApi\Common\AdsGuzzleProxyHttpHandler->__invoke(Object(GuzzleHttp\Psr7\Request))
#12 /code/vendor/google/auth/src/Credentials/UserRefreshCredentials.php(92): Google\Auth\OAuth2->fetchAuthToken(Object(Google\AdsApi\Common\AdsGuzzleProxyHttpHandler))
#13 /code/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/Util/OAuth2TokenRefresher.php(66): Google\Auth\C ... zleProxyHttpHandler))
#15 /code/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php(114): Google\AdsApi\AdWords\AdWordsHeaderHandler->generateHttpHeaders(Object(Google\AdsApi\AdWords\AdWordsSession))
#16 /code/vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdWords/v201802/mcm/ManagedCustomerService.php(103): Google\AdsApi\Common\AdsSoapClient->__soapCall('get', Array)
#17 /code/src/Keboola/AdWordsExtractor/Api.php(120): Google\AdsApi\AdWords\v201802\mcm\ManagedCustomerService->get(Object(Google\AdsApi\AdWords\v201802\cm\Selector))
#18 /code/src/Keboola/AdWordsExtractor/Extractor.php(78): Keboola\AdWordsExtractor\Api->getAllYielded(Object(Google\AdsApi\AdWords\v201802\mcm\ManagedCustomerService), Object(Google\AdsApi\AdWords\v201802\cm\Selector), 500)
#19 /code/src/Keboola/AdWordsExtractor/RunCommand.php(51): Keboola\AdWordsExtractor\Extractor->extract(Array, '20181107', '20181107')

https://keboola.slack.com/archives/C09U3R1J4/p1541642649004100

**Comment by odinuv** [comment]
neobjevilo se
